---
title: "PIB e IPC"
author: "Kamal Romero"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    social: menu
    vertical_layout: fill
    source_code: embed
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
#library(ggthemes)
load("PIB_OECD02.RData")
load("IPC_OECD2.RData")
```


Column {.sidebar}
=====================================

### Menu

```{r}
selectInput('pais', 'País', PIB_OECD02$LOCATION %>% unique())

```



PIB nominal y real
=====================================  

Column 
-----------------------------------------------------------------------

### Grafico 

```{r}
selectedData <- reactive({
  PIB_OECD02 %>%
  dplyr::filter(LOCATION == input$pais & MEASURE %in% c("C", "VOB") & label == "Gross domestic product (expenditure approach)"  & obsTime >=1995 ) %>% 
  select(obsTime, obsValue, MEASURE) %>%
  pivot_wider(names_from = MEASURE, values_from = obsValue) %>%
  rename(fecha = obsTime, Nominal = C, Real = VOB) 
})

renderPlotly({
  datos <- selectedData()
 grafico <- plot_ly(datos, x = ~fecha)
 grafico <- grafico %>% add_trace(y = ~Nominal, name = 'PIB Nominal', mode = 'lines+markers')
 grafico <- grafico %>% add_trace(y = ~Real, name = 'PIB Real', mode = 'lines+markers')
 f <- list(
  family = "Courier New, monospace",
  size = 18,
  color = "#7f7f7f"
  )
 x <- list(
  title = "Año",
  titlefont = f
  )
 y <- list(
  title = "PIB nominal y real",
  titlefont = f
  )
 grafico <- grafico %>% layout(xaxis = x, yaxis = y)

})
```


Componentes del PIB
=====================================



### Grafico 

```{r}
selectedData2 <- reactive({
  PIB_OECD02 %>% dplyr::filter(LOCATION == input$pais & TRANSACT %in% c("P31S14_S15", "P3S13", "P5", "B11") & MEASURE ==  "VOB" & obsTime >=1995 )
})

renderPlotly({
  datos2 <- selectedData2()
  transact.labs <- c("Consumo privado", "Consumo público", "Inversión", "XN")
  names(transact.labs) <- c("P31S14_S15", "P3S13", "P5", "B11")
  graf3 <- ggplot(datos2, aes(x=obsTime, y= obsValue, group=1))+
  geom_line(colour="#000099")+
  facet_wrap(~TRANSACT, labeller = labeller(TRANSACT=transact.labs), scales = "free")+
  labs(title = "Componentes del PIB")+
  xlab("Fecha")+
  ylab("Componentes")+
  scale_x_continuous(breaks = scales::breaks_width(4))
  ggplotly(graf3)
})
```

PIB real (variación porcentual)
=====================================

### Grafico 

```{r}
selectedData3 <- reactive({
  PIB_OECD02 %>% dplyr::filter(LOCATION == input$pais & MEASURE == "G" & label == "Gross domestic product (expenditure approach)"  & obsTime >=1995 )
})

renderPlotly({
  datos3 <- selectedData3()
  grafico2 <- plot_ly(datos3, x = ~obsTime)
  grafico2 <- grafico2 %>% add_trace(y = ~obsValue, name = 'Variación PIB Real', mode = 'lines+markers')
  f <- list(
    family = "Courier New, monospace",
    size = 18,
    color = "#7f7f7f"
  )
  x <- list(
    title = "Año",
    titlefont = f
  )
  y <- list(
    title = "Variación PIB real (%)",
    titlefont = f
  )
  grafico2 <- grafico2 %>% layout(xaxis = x, yaxis = y)
})
```


Componentes del PIB (variación porcentual)
=====================================


### Grafico 

```{r}
selectedData4 <- reactive({
  PIB_OECD02 %>% dplyr::filter(LOCATION == input$pais & TRANSACT %in% c("P31S14_S15", "P3S13", "P5", "B11") & MEASURE ==  "G" & obsTime >=1995 )
})

renderPlotly({
  datos4 <- selectedData4()
  transact.labs <- c("Consumo privado", "Consumo público", "Inversión", "XN")
  names(transact.labs) <- c("P31S14_S15", "P3S13", "P5", "B11")
  graf4 <- ggplot(datos4, aes(x=obsTime, y= obsValue, group=1))+
  geom_line(colour="#000099")+
  facet_wrap(~TRANSACT, labeller = labeller(TRANSACT=transact.labs), scales = "free")+
  labs(title = "Componentes del PIB")+
  xlab("Fecha")+
  ylab("Variación porcentual (%)")+
  scale_x_continuous(breaks = scales::breaks_width(4))
  ggplotly(graf4)
})
```


IPC (indice)
=====================================  

Column 
-----------------------------------------------------------------------

### Grafico 

```{r}
selectedData5 <- reactive({
  IPC_OECD2 %>%
  dplyr::filter(LOCATION == input$pais & UNIT =="IDX") %>% 
  select(obsTime, obsValue)
})

renderPlotly({
  datos5 <- selectedData5()
 grafico5 <- plot_ly(datos5, x = ~obsTime, y=~obsValue)
 grafico5 <- grafico5 %>% add_lines(y = ~obsValue, name = 'IPC', mode = 'lines')
 f <- list(
  family = "Courier New, monospace",
  size = 18,
  color = "#7f7f7f"
  )
 x <- list(
  title = "Año",
  titlefont = f
  )
 y <- list(
  title = "IPC (índice)",
  titlefont = f
  )
 grafico5 <- grafico5 %>%
   layout(xaxis = x, yaxis = y) %>% 
   layout(xaxis = list(
              rangeslider = list(type = "date")
              )
          )

})
```

Inflacion (variacion IPC)
=====================================  

Column 
-----------------------------------------------------------------------

### Grafico 

```{r}
selectedData6 <- reactive({
  IPC_OECD2 %>%
  dplyr::filter(LOCATION == input$pais & UNIT =="PC") %>% 
  select(obsTime, obsValue)
})

renderPlotly({
  datos6 <- selectedData6()
 grafico6 <- plot_ly(datos6, x = ~obsTime, y=~obsValue)
 grafico6 <- grafico6 %>% add_lines(y = ~obsValue, name = 'Inflación', mode = 'lines')
 f <- list(
  family = "Courier New, monospace",
  size = 18,
  color = "#7f7f7f"
  )
 x <- list(
  title = "Año",
  titlefont = f
  )
 y <- list(
  title = "Inflación (variación % IPC)",
  titlefont = f
  )
 grafico6 <- grafico6 %>% 
   layout(xaxis = x, yaxis = y) %>% 
   layout(xaxis = list(
              rangeslider = list(type = "date")
              )
          )

})
```
